SmsCrud/SmsCrud.WebMVC/Controllers/ContentController.cs
using SmsCrud.Model;
using SmsCrud.Repository;

namespace SmsCrud.WebMVC.Controllers
{
    public class ContentController : MainController<Content>
    {

        public ContentController(ContentRepository contentRepository): base(contentRepository)
        {
          
        }
    }
}

SmsCrud/SmsCrud.WebMVC/Controllers/ContentDataController.cs
using SmsCrud.Model;
using SmsCrud.Repository;

namespace SmsCrud.WebMVC.Controllers
{
    public class ContentDataController : MainController<ContentData>
    {
        public ContentDataController(ContentDataRepository contentDataRepository) : base(contentDataRepository)
        {

        }

    }
}

SmsCrud/SmsCrud.WebMVC/Controllers/MainController.cs
using System.Web.Mvc;
using SmsCrud.Repository;

namespace SmsCrud.WebMVC.Controllers
{
    public abstract class MainController<T> : Controller where T : class
    {

        private readonly Repo<T> _repo; 

        protected MainController(Repo<T> repo )
        {
            _repo = repo;
        }

        [HttpPost]
        public ActionResult Index(T t)
        {
            bool result = _repo.Save(t);
            return View();
            //return Json(new
            //{
            //    Result = result ? "Success" : "Failed",
            //    Message = result ? "Sucessfully Added User" : "Error occured while Deleting"
            //});
        }

        public JsonResult DeleteUser(int id)
        {
           bool result =  _repo.Delete(id);
            return Json(new
            {
                Result = result ? "Success" : "Failed",
                Message = result ? "Sucessfully Deleted User" : "Error occured while Deleting"
            });
        }

        public ActionResult EditUser(int id)
        {
            var model = _repo.Edit(id);
            return View(model);
        }


        public JsonResult SaveEdit(T t)
        {
            bool result = _repo.SaveEdit(t);

            return Json(new 
            {
                Result = result ? "Success" : "Failed",
                Message = result ? "Sucessfully Edited User" : "Error occured while Deleting"
            });
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult FindAll(int offset, int rowNumber, string sortExpression, string sortOrder, int pageNumber)
        {
            return Json(_repo.FindAll(offset, rowNumber, sortExpression, sortOrder, pageNumber));
        }

    }
}

SmsCrud/SmsCrud.WebMVC/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmsCrud.Model;
using SmsCrud.Repository;

namespace SmsCrud.WebMVC.Controllers
{
    public class ServiceController : MainController<Service>
    {

        public ServiceController(ServiceRepository serviceRepository) : base(serviceRepository)
        {
        }

    }
}

SmsCrud/SmsCrud.WebMVC/Views/Content/EditUser.cshtml
@{
    Layout = null;
    @model SmsCrud.Model.Content
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditUser</title>
</head>
<body>
<div>
    
   @using (@Html.BeginForm("SaveEdit", "Content", FormMethod.Post, new {@class = "form-horizontal", @id="content-form"}))
    {

        @Html.HiddenFor(x => x.Id, new {@class = "form-control"})

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.DefaultName, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.DefaultName, new {@class = "form-tb"}) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.IsManual, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.IsManual, new {@class = "form-tb"}) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.Active, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.Active, new {@class = "form-tb"}) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.WorkName, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.WorkName, new {@class = "form-tb"}) </div>
        </div>


        <div class="row-fluid">
            <input type="button" name="SubmitLogin" id="save-edit" value="Update" class="btn btn-danger right"/>
            <input type="button" name="SubmitLogin" id="btn_cancel" value="Cancel" onclick=" closeDialog(this)"  class=" btn btn-danger right" />
        </div>



   }
</div>


<script>
    $(function() {


    });
    debugger;
    $("#save-edit").click(function () {
        $.ajax({
            url: '@Url.Action("SaveEdit","Content")',
            type: "post",
            data: $("#content-form").serialize(),
            dataType: "json",
            success: function (response) {
                 if (response.Result == "Success") {
                   showSuccessMessage("message", response.Message);
                  }
                $("#btn_cancel").trigger("click");
                $("#content-list").trigger('refresh');
            }

        });
    });
</script>

</body>
</html>

SmsCrud/SmsCrud.WebMVC/Views/Content/EditView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditView</title>
</head>
<body>
    <div>
       @using (@Html.BeginForm("Index", "Content", FormMethod.Post, new { @class = "form-horizontal" }))
       {

        @Html.HiddenFor(x => x.Id, new { @class = "form-control" })

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.DefaultName, new { @class = "form-lbl" }) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.DefaultName, new { @class = "form-tb" }) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.IsManual, new { @class = "form-lbl" }) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.IsManual, new { @class = "form-tb" }) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.Active, new { @class = "form-lbl" }) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.Active, new { @class = "form-tb" }) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.WorkName, new { @class = "form-lbl" }) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.WorkName, new { @class = "form-tb" }) </div>
        </div>


        <div class="form-group">
            <input type="submit" name="SubmitLogin" value="Save" class="btn btn-danger right" />
        </div>



       }
    </div>
</body>
</html>

SmsCrud/SmsCrud.WebMVC/Views/Content/Index.cshtml
@{
    ViewBag.Title = "Index";
    @model SmsCrud.Model.Content

}


    <div class="row-fluid form-group">
        <div id="message" style="display: none"></div>
    </div>

    <div class="content maincontainer">
        <div class="col-xs-3">
            @using (@Html.BeginForm("Index", "Content", FormMethod.Post, new {@class = "form-horizontal"}))
            {

                @Html.HiddenFor(x => x.Id, new {@class = "form-control"})

                <div class="form-group">
                    <div class="col-xs-4"> @Html.LabelFor(x => x.DefaultName, new {@class = "form-lbl"}) </div>
                    <div class="col-xs-8"> @Html.TextBoxFor(x => x.DefaultName, new {@class = "form-tb"}) </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-4"> @Html.LabelFor(x => x.IsManual, new {@class = "form-lbl"}) </div>
                    <div class="col-xs-8"> @Html.TextBoxFor(x => x.IsManual, new {@class = "form-tb"}) </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-4"> @Html.LabelFor(x => x.Active, new {@class = "form-lbl"}) </div>
                    <div class="col-xs-8"> @Html.TextBoxFor(x => x.Active, new {@class = "form-tb"}) </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-4"> @Html.LabelFor(x => x.WorkName, new {@class = "form-lbl"}) </div>
                    <div class="col-xs-8"> @Html.TextBoxFor(x => x.WorkName, new {@class = "form-tb"}) </div>
                </div>


                <div class="row-fluid">
                    <input type="submit" name="SubmitLogin" value="Save" class="btn btn-danger right"/>
                </div>



            }
        </div>


    <div class="col-xs-9">
        <div class="row-fluid">
            <table class="table table-bordered table-responsive table-striped" id="content-list">
                <thead>
                <tr>
                    <th>
                        <a class="table-header" field-name="Id">
                            Id
                        </a>
                    </th>
                    <th>
                        <a class="table-header" field-name="DefaultName">
                            Default Name
                        </a>
                    </th>
                    <th>
                        <a class="table-header" field-name="Active">
                            IsManual
                        </a>
                    </th>
                    <th>
                        <a class="table-header" field-name="IsManual">
                            Active
                        </a>
                    </th>
                    <th>
                        <a class="table-header" field-name="WorkName">
                            WorkName
                        </a>
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>
                </thead>
                <tbody></tbody>
            </table>
            <div id="loading-msg" class="loading-image">
            </div>
        </div>
    </div>
        </div>

<script>
    $(function() {

      
        $("#content-list").ajaxGrid({
            pageSize: 20,
            defaultSortExpression: 'Id',
            defaultSortOrder: 'asc',
            tableHeading: '.table-header',
            url: '@Url.Action("FindAll","Content")',
            requestType: 'post',
            loadingImage: $('#loading-msg'),
            NoRecordsFound: 'No Records Found',
            postContent: [
                  {
                      control: $('<button type="button" class="btn btn-primary" ' +
                          'onclick=\'showEditForm(this,"Edit","@Url.Action("EditUser","Content")",400,300,"user-loading-message")\'>' +
                          '<small class="glyphicon glyphicon-edit"></small>' +
                          ' Edit </button>')
                  },
                  {
                      control: $('<button type="submit" class="btn btn-danger" ' +
                          'onclick=\'return deleteRecord(this,"user-loading-message","Content/DeleteUser","Are you sure you want to Delete?","refreshContent()")\'>' +
                          '<small class="glyphicon glyphicon-remove"></small>' +
                          ' Delete </button>'),
                      properties: [
                          {
                              propertyField: 'input[type=hidden]#ID',
                              property: 'value',
                              propertyValue: 'ID'
                          }
                      ],
                      removeWhen: { property: 'UserType', value: 'Admin' }
                  }
            ],
            id: 'Id',
            success: function (response) {
                console.log(response);
            }
        });
    });
    debugger;
    function refreshContent() {
        $("#content-list").trigger('refresh');
    }
</script>

SmsCrud/SmsCrud.WebMVC/Views/Content/SaveEdit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SaveEdit</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>

SmsCrud/SmsCrud.WebMVC/Views/Content/Test.cshtml
@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>

SmsCrud/SmsCrud.WebMVC/Views/ContentData/EditUser.cshtml
@{
    Layout = null;
    @model SmsCrud.Model.ContentData
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditUser</title>
</head>
<body>
<div>
    @using (@Html.BeginForm("Index", "ContentData", FormMethod.Post, new {@class = "form-horizontal", @id = "contentData-form"}))
    {

        @Html.HiddenFor(x => x.Id, new {@class = "form-control"})

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.Text, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.Text, new {@class = "form-tb"}) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.ContentID, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.ContentID, new {@class = "form-tb"}) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.DatetimeInserted, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.DatetimeInserted, new {@class = "form-tb"}) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.Language, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.Language, new {@class = "form-tb"}) </div>
        </div>

        <div class="form-group">
            <div class="col-xs-4"> @Html.LabelFor(x => x.SpecificParam, new {@class = "form-lbl"}) </div>
            <div class="col-xs-8"> @Html.TextBoxFor(x => x.SpecificParam, new {@class = "form-tb"}) </div>
        </div>

        <div class="row-fluid">
            <input type="button" name="SubmitLogin" id="save-edit" value="Save" class="btn btn-danger right"/>
            <input type="button" name="SubmitLogin" id="btn_cancel" value="Cancel" onclick=" closeDialog(this) " class="btn btn-danger right"/>
        </div>
    }
</div>

    <script>
    $(function() {


    });
    debugger;
    $("#save-edit").click(function () {
        $.ajax({
            url: '@Url.Action("SaveEdit","ContentData")',
            type: "post",
            data: $("#contentData-form").serialize(),
            dataType: "json",
            success: function (response) {
                 if (response.Result == "Success") {
                   showSuccessMessage("message", response.Message);
                  }
                $("#btn_cancel").trigger("click");
                $("#contentData-list").trigger('refresh');
            }
        });
    });
    </script>


</body>
</html>

SmsCrud/SmsCrud.WebMVC/Views/ContentData/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @model SmsCrud.Model.ContentData
}


<div class="row-fluid form-group">
    <div id="message" style="display: none"></div>
</div>

<div class="content maincontainer">
    <div class="col-xs-3">
        @using (@Html.BeginForm("Index", "ContentData", FormMethod.Post, new { @class = "form-horizontal" }))
        {

            @Html.HiddenFor(x => x.Id, new { @class = "form-control" })

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.Text, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.Text, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.ContentID, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.ContentID, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.DatetimeInserted, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.DatetimeInserted, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.Language, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.Language, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.SpecificParam, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.SpecificParam, new { @class = "form-tb" }) </div>
            </div>

            <div class="row-fluid">
                <input type="submit" name="SubmitLogin" value="Save" class="btn btn-danger right" />
            </div>



        }
    </div>


    <div class="col-xs-9">
        <div class="row-fluid">
            <table class="table table-bordered table-responsive table-striped" id="contentData-list">
                <thead>
                    <tr>
                        <th>
                            <a class="table-header" field-name="Id">
                                Id
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="ContentID">
                                ContentID
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="DatetimeInserted">
                                DatetimeInserted
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="SpecificParam">
                                SpecificParam
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="Language">
                                Language
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="Text">
                                Text
                            </a>
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
            <div id="loading-msg" class="loading-image">
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {


        $("#contentData-list").ajaxGrid({
            pageSize: 20,
            defaultSortExpression: 'Id',
            defaultSortOrder: 'asc',
            tableHeading: '.table-header',
            url: '@Url.Action("FindAll","ContentData")',
            requestType: 'post',
            loadingImage: $('#loading-msg'),
            NoRecordsFound: 'No Records Found',
            postContent: [
                  {
                      control: $('<button type="button" class="btn btn-primary" ' +
                          'onclick=\'showEditForm(this,"Edit","@Url.Action("EditUser","ContentData")",400,350,"user-loading-message")\'>' +
                          '<small class="glyphicon glyphicon-edit"></small>' +
                          ' Edit </button>')
                  },
                  {
                      control: $('<button type="submit" class="btn btn-danger" ' +
                          'onclick=\'return deleteRecord(this,"user-loading-message","ContentData/DeleteUser","Are you sure you want to Delete?","refreshContent()")\'>' +
                          '<small class="glyphicon glyphicon-remove"></small>' +
                          ' Delete </button>'),
                      properties: [
                          {
                              propertyField: 'input[type=hidden]#ID',
                              property: 'value',
                              propertyValue: 'ID'
                          }
                      ],
                      removeWhen: { property: 'UserType', value: 'Admin' }
                  }
            ],
            id: 'Id',
            success: function (response) {
                console.log(response);
            }
        });
    });
    debugger;
    function refreshContent() {
        $("#contentData-list").trigger('refresh');
    }
</script>

SmsCrud/SmsCrud.WebMVC/Views/ContentData/SaveEdit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SaveEdit</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>

SmsCrud/SmsCrud.WebMVC/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Index";
    @model SmsCrud.Model.Content
    
}

<h1> COntent View </h1>

SmsCrud/SmsCrud.WebMVC/Views/Service/Index.cshtml
@{
    ViewBag.Title = "Index";
    @model SmsCrud.Model.Service

}


<div class="row-fluid form-group">
    <div id="message" style="display: none"></div>
</div>

<div class="content maincontainer">
    <div class="col-xs-3">
        @using (@Html.BeginForm("Index", "Content", FormMethod.Post, new { @class = "form-horizontal" }))
        {

            @Html.HiddenFor(x => x.ID, new { @class = "form-control" })

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.OperatorID, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.OperatorID, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.ContentID, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.ContentID, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.ContentName, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.ContentName, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.ContentGenerationType, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.ContentGenerationType, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.EndTime, new {@class = "form-lbl"}) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.EndTime, new {@class = "form-tb"}) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.FOCsms, new {@class = "form-lbl"}) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.FOCsms, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.FireTime, new {@class = "form-lbl"}) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.FireTime, new {@class = "form-tb"}) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.BillingGateID, new {@class = "form-lbl"}) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.BillingGateID, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.Sender, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.Sender, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.SMSGateID, new { @class = "form-lbl" }) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.SMSGateID, new { @class = "form-tb" }) </div>
            </div>

            <div class="form-group">
                <div class="col-xs-4"> @Html.LabelFor(x => x.SMSonTrialEnd, new {@class = "form-lbl"}) </div>
                <div class="col-xs-8"> @Html.TextBoxFor(x => x.SMSonTrialEnd, new {@class = "form-tb"}) </div>
            </div>

    <div class="form-group">
        <div class="col-xs-4"> @Html.LabelFor(x => x.SMSonTrialEnd, new { @class = "form-lbl" }) </div>
        <div class="col-xs-8"> @Html.TextBoxFor(x => x.SMSonTrialEnd, new { @class = "form-tb" }) </div>
    </div>





            <div class="row-fluid">
                <input type="submit" name="SubmitLogin" value="Save" class="btn btn-danger right" />
            </div>



        }
    </div>


    <div class="col-xs-9">
        <div class="row-fluid">
            <table class="table table-bordered table-responsive table-striped" id="content-list">
                <thead>
                    <tr>
                        <th>
                            <a class="table-header" field-name="Id">
                                Id
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="DefaultName">
                                Default Name
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="Active">
                                IsManual
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="IsManual">
                                Active
                            </a>
                        </th>
                        <th>
                            <a class="table-header" field-name="WorkName">
                                WorkName
                            </a>
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
            <div id="loading-msg" class="loading-image">
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {


        $("#content-list").ajaxGrid({
            pageSize: 20,
            defaultSortExpression: 'Id',
            defaultSortOrder: 'asc',
            tableHeading: '.table-header',
            url: '@Url.Action("FindAll","Content")',
            requestType: 'post',
            loadingImage: $('#loading-msg'),
            NoRecordsFound: 'No Records Found',
            postContent: [
                  {
                      control: $('<button type="button" class="btn btn-primary" ' +
                          'onclick=\'showEditForm(this,"Edit","@Url.Action("EditUser","Content")",400,300,"user-loading-message")\'>' +
                          '<small class="glyphicon glyphicon-edit"></small>' +
                          ' Edit </button>')
                  },
                  {
                      control: $('<button type="submit" class="btn btn-danger" ' +
                          'onclick=\'return deleteRecord(this,"user-loading-message","Content/DeleteUser","Are you sure you want to Delete?","refreshContent()")\'>' +
                          '<small class="glyphicon glyphicon-remove"></small>' +
                          ' Delete </button>'),
                      properties: [
                          {
                              propertyField: 'input[type=hidden]#ID',
                              property: 'value',
                              propertyValue: 'ID'
                          }
                      ],
                      removeWhen: { property: 'UserType', value: 'Admin' }
                  }
            ],
            id: 'Id',
            success: function (response) {
                console.log(response);
            }
        });
    });
    debugger;
    function refreshContent() {
        $("#content-list").trigger('refresh');
    }
</script>

SmsCrud/SmsCrud.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Styles/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>

    <div class="container-fluid">
        <nav class="nav navbar-static-top navbar-inverse">
            <div class="navbar-header">
                <div class="navbar-brand headerText"> SMS CRUD </div>

            </div>

            <ul class="nav-tab pull-right">
                <a href="@Url.Action("Index","Content")">
                    <li> Content </li>
                </a>

                <a href="@Url.Action("Index", "ContentData")">
                    <li> ContentData </li>
                </a>

                <a href="#">
                    <li> Subscription </li>
                </a>

                <a href="@Url.Action("Index","Service")">
                    <li> Service </li>
                </a>

            </ul>
        </nav>

    

    @RenderBody()
</div>


</body>
</html>